config/routes.rb
Rails.application.routes.draw do
  resources :articles

  devise_for :users
  resources :users

  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_and_belongs_to_many :users
  validates :name, presence: true
  validates :content, presence: true
end

app/models/articles_users.rb
class ArticlesUsers < ActiveRecord::Base
  belongs_to :users
  belongs_to :articles
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate_user!, only: [:edit, :new, :create, :update]
  def index
    @articles = Article.all.order(created_at: :desc)
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create(article_params)
    if @article.save
      @article.users << current_user
      redirect_to article_path(@article), notice: 'Article Successfully Created'
    else
      redirect_to new_article_path, notice: "Come On Guy, don't be stupid."
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      @article.users << current_user
      redirect_to article_path(@article), notice: 'Article Successfully Updated'
    else
      redirect_to edit_article_path(@article), notice: "Come On Guy, don't be stupid."
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path, notice: 'Article was successfully destroyed.'
  end

  private

  def article_params
    params.require(:article).permit(:name, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    # Stuff
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
<%= render 'form' %>

app/views/articles/index.html.erb
<h2>Articles</h2>
<ul>
<% @articles.each do |a| %>
  <li><%= link_to a.name, article_path(a) %></li>
<% end %>
</ul>

<% unless current_user.nil? %>
<%= link_to "New Article", new_article_path %>
<% end %>

app/views/articles/new.html.erb
<%= render 'form' %>

app/views/articles/show.html.erb
<div class="article_title"><h2><%= @article.name %></h2></div>
<div class="article_content"><p><%= @article.content %></p></div>

<p>Editors:</p>
<ul>
<% @article.users.length.times do |u| %>
  <li><%= link_to @article.users[u].email, user_path(@article.users[u]) %></li>
<% end %>
</ul>

<% unless current_user.nil? %>
<%= link_to "Edit", edit_article_path(@article), class: "button" %><%= link_to "Delete", article_path(@article), method: "delete", data: {confirm: "Are you sure?"}, class: "button" %>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "RonWiki", root_path %></h1>
    </li>
  </ul>
  <section class="top-bar-section">
    <ul class="right">
      <li class="divider"></li>
      <li><%= link_to "Articles", articles_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Users", users_path %></li>
      <% if current_user.nil? %>
      <li class="divider"></li>
      <li><%= link_to "Sign In", new_user_session_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <% else %>
      <li class="divider"></li>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: "delete" %></li>
      <% end %>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

<div class="row">
  <body>
    <%= render 'layouts/nav' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</div>
</html>

app/views/users/index.html.erb
<h2>Users</h2>
<ul>
<% @users.each do |u| %>
  <li><%= link_to u.email, user_path(u) %></li>
<% end %>
</ul>

app/views/users/show.html.erb
<h2><%= @user.email %></h2>

Articles:
<ul>
<% @user.articles.length.times do |u| %>
  <li><%= link_to @user.articles[u].name, article_path(@user.articles[u]) %></li>
<% end %>
</ul>

app/views/welcome/index.html.erb
<h1>Wiki</h1>